#!/usr/bin/env bash
set -euo pipefail

python3 - <<'PY'
import re
from pathlib import Path
from datetime import datetime

def parse_frontmatter(text):
    match = re.search(r"^---\n(.*?)\n---\n", text, re.S)
    if not match:
        return {}
    front = match.group(1)
    data = {}
    for line in front.splitlines():
        if re.match(r"^[a-zA-Z_].*:\s*", line):
            key, val = line.split(":", 1)
            data[key.strip()] = val.strip()

    # description block handling
    if "description" in data and data["description"] in ("|", ">"):
        lines = front.splitlines()
        desc_lines = []
        capture = False
        for line in lines:
            if line.startswith("description:"):
                capture = True
                continue
            if capture:
                if re.match(r"^[a-zA-Z_].*:\s*", line):
                    break
                desc_lines.append(line.strip())
        data["description"] = " ".join([d for d in desc_lines if d])

    return data

# Pack membership
pack_map = {}
for pack_file in Path("skill-packs").glob("*/PACK.md"):
    text = pack_file.read_text(encoding="utf-8")
    front = parse_frontmatter(text)
    skills = []
    block = re.search(r"^---\n(.*?)\n---\n", text, re.S)
    if block:
        lines = block.group(1).splitlines()
        in_skills = False
        for line in lines:
            if line.startswith("skills:"):
                in_skills = True
                continue
            if in_skills:
                if re.match(r"^[a-zA-Z_].*:\s*", line):
                    break
                m = re.match(r"\s*-\s*(.+)", line)
                if m:
                    skills.append(m.group(1).strip())
    for skill in skills:
        pack_map.setdefault(skill, []).append(front.get("name", pack_file.parent.name))

skills_by_name = {}

def add_skill(skill_file):
    data = parse_frontmatter(skill_file.read_text(encoding="utf-8"))
    name = data.get("name", skill_file.parent.name)
    if name in skills_by_name:
        return
    skills_by_name[name] = {
        "name": name,
        "description": data.get("description", ""),
        "version": data.get("version", ""),
        "tier": data.get("tier", ""),
        "category": data.get("category", ""),
        "packs": ", ".join(sorted(pack_map.get(name, []))) or "-",
    }

for skill_file in sorted(Path("skill-packs").glob("*/*/SKILL.md")):
    add_skill(skill_file)

for skill_file in sorted(Path("skills").glob("*/SKILL.md")):
    add_skill(skill_file)

skills = list(skills_by_name.values())

categories = sorted({s["category"] for s in skills})

lines = []
lines.append("# Skill Catalog")
lines.append("")
lines.append("Generated by `scripts/generate-catalog.sh`.")
lines.append("")

for category in categories:
    lines.append(f"## {category.title()}")
    lines.append("")
    lines.append("| Skill | Description | Version | Tier | Packs |")
    lines.append("|-------|-------------|---------|------|-------|")
    for s in sorted([x for x in skills if x["category"] == category], key=lambda x: x["name"]):
        desc = s["description"].replace("|", "\\|")
        lines.append(f"| `{s['name']}` | {desc} | {s['version']} | {s['tier']} | {s['packs']} |")
    lines.append("")

Path("CATALOG.md").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
print("Wrote CATALOG.md")
PY
